spring:
  application:
    name: autores-api
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/autores}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  #Perfil definido nas linhas abaixo apontando para arquivo separado ou para configuração no final deste arquivo após '---'
  #Opção: variável de ambiente SPRING_PROFILES_ACTIVE
#  profiles:
#    active: prd

#springdoc-openapi - https://springdoc.org/
#Swagger API page default - http://server:port/context-path/swagger-ui.html
springdoc:
  swagger-ui:
    path: /docs
  override-with-generic-response: false

#root, sql ou web
#trace, debug, info, warn, error, fatal, off
logging:
  pattern:
    dateformat: dd-MM-yyyy'T'HH:mm:ss.SSSXXX
  file:
    name: autores-api.log
  level:
    root: debug
    br:
      com:
        atavares:
          autoresapi: debug

#Observabilidade com Spring Boot Starter Actuator
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

---

#Configurações de produção
spring:
  config:
    activate:
      on-profile: prod

logging:
  pattern:
    dateformat: dd-MM-yyyy'T'HH:mm:ss.SSSXXX
  file:
    name: autores-api.log
  level:
    root: warn
    br:
      com:
        atavares:
          autoresapi: warn